from .assunto import Assunto
from .campus import Campus
from .cargo import Cargo
from .convite import Convite
from .curso import Curso
from .edificio import Edificio
from .erro_palavra import ErroPalavra
from .frase import Frase
from .instituicao import Instituicao
from .palavras import Palavra
from .peso_palavra import PesoPalavra
from .recurso import Recurso
from .reserva import Reserva
from .resposta import Resposta
from .sala import Sala
from .sala_recurso import SalaRecurso
from .status_reserva import StatusReserva
#from .tabela import Tabela
from .tipo_sala import TipoSala
from .tipo_sala_recurso import TipoSalaRecurso
from .usuario import Usuario