from .assunto import Assunto
from .cargos import Cargo
from .curso import Curso
from .erro_palavra import ErroPalavra
from .frase import Frase
from .palavras import Palavra
from .peso_palavra import PesoPalavra
from .recurso import Recurso
from .reserva import Reserva
from .resposta import Resposta
from .sala_recurso import SalaRecurso
from .sala import Sala
from .status_reserva import StatusReserva
from .tabela import Tabela
from .tipo_sala import TipoSala
from .usuario import Usuario